name: learning
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: echo hai

      - name: Install databricks cli
        run: pip install databricks-cli
