name: learning
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: echo hai

      - name: Install databricks cli
        run: pip install databricks-cli

      - name: Get token
        run: |
            response=$(curl -s -X POST "https://login.microsoftonline.com/9a8cd433-6113-49e5-aa7f-42788a01a246/oauth2/token" \
            -F grant_type=client_credentials \
            -F client_id="8d7e7b20-d0d0-48ae-af7b-73ab6e1b8f5b" \
            -F client_secret=".oh8Q~aOlsaJvixJ8.enkWU-C300j7yyYARgndlc" \
            -F resource="2ff814a6-3304-4ab8-85cb-cd0e6f879c1d") 
            
            access_token=$(echo "$response" | jq -r '.access_token')
            echo "$access_token"
            echo "::add-mask::$access_token"
            echo "access_token=$access_token" >> $GITHUB_OUTPUT
